# Generated by Django 2.1 on 2018-08-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxDeviceDataType',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='数据类型名称')),
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='数据类型标识')),
            ],
            options={
                'verbose_name': '数据类型名称',
                'verbose_name_plural': '数据类型名称',
            },
        ),
        migrations.CreateModel(
            name='boxDeviceHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to='', verbose_name='原始报文')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='boxDeviceTable',
            fields=[
                ('boxID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='boxID')),
                ('boxNum', models.IntegerField(default=0, verbose_name='箱号')),
                ('chnNum', models.IntegerField(default=0, verbose_name='通道号')),
                ('boxIP', models.GenericIPAddressField(default='192.168.1.1', verbose_name='IP地址')),
                ('boxPort', models.IntegerField(default=0, verbose_name='端口号')),
            ],
        ),
        migrations.CreateModel(
            name='cellDeviceTable',
            fields=[
                ('cellID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='cellID')),
                ('boxNum', models.IntegerField(default=0, verbose_name='箱号')),
                ('chnNum', models.IntegerField(default=0, verbose_name='通道号')),
                ('i', models.IntegerField(default=0, verbose_name='实时电流')),
                ('u', models.IntegerField(default=0, verbose_name='实时电压')),
                ('q', models.IntegerField(default=0, verbose_name='实时容量')),
                ('qA', models.IntegerField(default=0, verbose_name='累计容量')),
                ('r', models.IntegerField(default=0, verbose_name='当前内阻')),
                ('T', models.IntegerField(default=0, verbose_name='当前温度')),
                ('n', models.IntegerField(default=0, verbose_name='当前工步号')),
                ('k', models.IntegerField(default=0, verbose_name='当前过程号')),
                ('state', models.IntegerField(default=0, verbose_name='通道状态')),
                ('mode', models.IntegerField(default=0, verbose_name='工作模式')),
                ('tc', models.IntegerField(default=0, verbose_name='本工步已完成时间')),
                ('ta', models.IntegerField(default=0, verbose_name='本工步累计时间')),
                ('celldata_time', models.DateTimeField(auto_now=True, verbose_name='电池数据修改时间')),
                ('qH2', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='H2流量')),
                ('qN2', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='N2流量')),
                ('qCH4', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='CH4流量')),
                ('qAIR', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='空气流量')),
                ('qH2O', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='水流量')),
                ('gasdata_time', models.DateTimeField(auto_now=True, verbose_name='气体数据修改时间')),
                ('T1', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='温度监测点1')),
                ('T2', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='温度监测点2')),
                ('T3', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='温度监测点3')),
            ],
        ),
        migrations.CreateModel(
            name='gasDeviceDataType',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='数据类型名称')),
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='数据类型标识')),
            ],
            options={
                'verbose_name': '数据类型名称',
                'verbose_name_plural': '数据类型名称',
            },
        ),
        migrations.CreateModel(
            name='gasDeviceHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to='', verbose_name='原始报文')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='gasDeviceTable',
            fields=[
                ('gasID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='气体流量计的ID')),
                ('qCoef', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2, verbose_name='比例系数')),
                ('qIP', models.GenericIPAddressField(default='192.168.1.2', verbose_name='IP地址')),
                ('qPort', models.IntegerField(default=0, verbose_name='端口号')),
                ('cellID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.cellDeviceTable', verbose_name='cellID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.gasDeviceDataType', verbose_name='数据类型标识')),
            ],
        ),
        migrations.AddField(
            model_name='gasdevicehistorydata',
            name='gasID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.gasDeviceTable', verbose_name='gasID'),
        ),
        migrations.AddField(
            model_name='gasdevicehistorydata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.gasDeviceDataType', verbose_name='数据类型标识'),
        ),
        migrations.AddField(
            model_name='boxdevicetable',
            name='cellID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.cellDeviceTable', verbose_name='cellID'),
        ),
        migrations.AddField(
            model_name='boxdevicehistorydata',
            name='boxID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.boxDeviceTable', verbose_name='boxID'),
        ),
        migrations.AddField(
            model_name='boxdevicehistorydata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.boxDeviceDataType', verbose_name='数据类型标识'),
        ),
    ]
