# Generated by Django 2.1 on 2018-08-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldevicetable',
            name='cellID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='cellID'),
        ),
    ]
