# Generated by Django 2.1 on 2018-08-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20180810_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasdevicehistorydata',
            name='gasID',
        ),
        migrations.AddField(
            model_name='gasdevicehistorydata',
            name='cellID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.cellDeviceTable', verbose_name='cellID'),
            preserve_default=False,
        ),
    ]
