# Generated by Django 2.1 on 2018-08-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180810_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxdevicetable',
            name='cellID',
        ),
    ]
