# Generated by Django 2.1 on 2018-08-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='系统ID(2开头6位)')),
                ('building_name', models.CharField(max_length=20, verbose_name='建筑物名')),
                ('p', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='有功功率')),
                ('q', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='无功功率')),
                ('u', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压')),
                ('i', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电流')),
                ('e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电表读数')),
                ('today_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='今日能耗')),
                ('yesterday_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='昨日能耗')),
                ('month_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本月能耗')),
                ('year_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本年能耗')),
                ('snr', models.CharField(default=0, editable=False, max_length=20, verbose_name='信噪比')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '建筑物信息',
                'verbose_name_plural': '建筑物信息',
            },
        ),
        migrations.CreateModel(
            name='Building_hour_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数')),
                ('add_e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数增量')),
                ('is_now', models.BooleanField(default=False, verbose_name='是否实时数据')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Building', verbose_name='建筑物')),
            ],
            options={
                'verbose_name': '建筑物_小时电量数据',
                'verbose_name_plural': '建筑物_小时电量数据',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='客户ID(0开头6位)')),
                ('name', models.CharField(max_length=50, verbose_name='客户名')),
                ('province', models.CharField(max_length=20, verbose_name='地址_省')),
                ('city', models.CharField(max_length=20, verbose_name='地址_市')),
                ('district', models.CharField(max_length=20, verbose_name='地址_区')),
                ('street', models.CharField(max_length=20, verbose_name='地址_街道')),
                ('terminal_online_rate', models.FloatField(default=0, editable=False, verbose_name='终端在线率')),
                ('count_terminal', models.IntegerField(default=0, editable=False, verbose_name='终端总数量')),
                ('count_lora', models.IntegerField(default=0, editable=False, verbose_name='LoRa终端数量')),
                ('count_nblot', models.IntegerField(default=0, editable=False, verbose_name='NBIoT终端数量')),
                ('count_wifi', models.IntegerField(default=0, editable=False, verbose_name='wifi终端数量')),
                ('count_4g', models.IntegerField(default=0, editable=False, verbose_name='4g终端数量')),
                ('count_all_device', models.IntegerField(default=0, editable=False, verbose_name='设备（表计）数量')),
                ('count_ammeter', models.IntegerField(default=0, editable=False, verbose_name='电表数量')),
                ('count_watermeter', models.IntegerField(default=0, editable=False, verbose_name='水表数量')),
                ('count_gasmeter', models.IntegerField(default=0, editable=False, verbose_name='气表数量')),
                ('count_othermeter', models.IntegerField(default=0, editable=False, verbose_name='其他设备（表计）数量')),
                ('p', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='有功功率')),
                ('q', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='无功功率')),
                ('u', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压')),
                ('i', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电流')),
                ('e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电表读数')),
                ('today_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='今日能耗')),
                ('yesterday_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='昨日能耗')),
                ('month_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本月能耗')),
                ('year_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本年能耗')),
                ('snr', models.CharField(default=0, editable=False, max_length=20, verbose_name='信噪比')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '客户园区信息',
                'verbose_name_plural': '客户园区信息',
            },
        ),
        migrations.CreateModel(
            name='Customer_hour_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数')),
                ('add_e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数增量')),
                ('is_now', models.BooleanField(default=False, verbose_name='是否实时数据')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户_小时电量数据',
                'verbose_name_plural': '客户_小时电量数据',
            },
        ),
        migrations.CreateModel(
            name='Data_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type_name', models.CharField(max_length=30, verbose_name='数据类型中文名称')),
                ('device_type', models.CharField(choices=[('ammeter', '电表'), ('watermeter', '水表'), ('gasmeter', '气表'), ('othermeter', '其他表')], max_length=20, verbose_name='表计类型')),
                ('data_type', models.CharField(max_length=30, unique=True, verbose_name='数据类型')),
            ],
            options={
                'verbose_name': '数据类型',
                'verbose_name_plural': '数据类型',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='系统ID')),
                ('device_name', models.CharField(max_length=20, verbose_name='设备/房间描述(位置、类型等)')),
                ('device_type', models.CharField(choices=[('ammeter_single', '单相电表'), ('ammeter_three', '三相电表'), ('watermeter', '水表'), ('gasmeter', '气表'), ('othermeter', '其他表')], max_length=20, verbose_name='表计类型')),
                ('ratio', models.IntegerField(default=1, verbose_name='系数（变比）')),
                ('active', models.BooleanField(default=True, verbose_name='表计是否激活/使用')),
                ('p', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='有功功率')),
                ('q', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='无功功率')),
                ('u', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压')),
                ('i', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电流')),
                ('e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电表读数')),
                ('today_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='今日能耗')),
                ('yesterday_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='昨日能耗')),
                ('month_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本月能耗')),
                ('year_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本年能耗')),
                ('snr', models.CharField(default=0, editable=False, max_length=20, verbose_name='信噪比')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicebui', to='apps.Building', verbose_name='所属建筑物')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicecus', to='apps.Customer', verbose_name='所属客户园区')),
            ],
            options={
                'verbose_name': '设备/房间信息',
                'verbose_name_plural': '设备/房间信息',
            },
        ),
        migrations.CreateModel(
            name='Device_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='数据值')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='数据时间')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Data_type', to_field='data_type', verbose_name='数据类型')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Device', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '设备数据',
                'verbose_name_plural': '设备数据',
            },
        ),
        migrations.CreateModel(
            name='Device_hour_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数')),
                ('add_e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数增量')),
                ('is_now', models.BooleanField(default=False, verbose_name='是否实时数据')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备_小时电量数据',
                'verbose_name_plural': '设备_小时电量数据',
            },
        ),
        migrations.CreateModel(
            name='Device_p_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=20, verbose_name='系统ID')),
                ('p', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='有功功率')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='数据时间')),
            ],
            options={
                'verbose_name': '设备_有功功率历史数据',
                'verbose_name_plural': '设备_有功功率历史数据',
            },
        ),
        migrations.CreateModel(
            name='Energy_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type_name', models.CharField(max_length=30, verbose_name='能耗类型中文名称')),
                ('energy_type', models.CharField(max_length=30, unique=True, verbose_name='能耗类型')),
            ],
            options={
                'verbose_name': '能耗类型',
                'verbose_name_plural': '能耗类型',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='系统ID(3开头6位)')),
                ('floor_name', models.CharField(max_length=20, verbose_name='楼层名')),
                ('p', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='有功功率')),
                ('q', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='无功功率')),
                ('u', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压')),
                ('i', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电流')),
                ('e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电表读数')),
                ('today_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='今日能耗')),
                ('yesterday_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='昨日能耗')),
                ('month_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本月能耗')),
                ('year_e', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='本年能耗')),
                ('snr', models.CharField(default=0, editable=False, max_length=20, verbose_name='信噪比')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='apps.Building', verbose_name='所属建筑物')),
            ],
            options={
                'verbose_name': '楼层信息',
                'verbose_name_plural': '楼层信息',
            },
        ),
        migrations.CreateModel(
            name='Floor_hour_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数')),
                ('add_e', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='电表读数增量')),
                ('is_now', models.BooleanField(default=False, verbose_name='是否实时数据')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Floor', verbose_name='楼层')),
            ],
            options={
                'verbose_name': '楼层_小时电量数据',
                'verbose_name_plural': '楼层_小时电量数据',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='协议类型')),
            ],
            options={
                'verbose_name': '协议信息',
                'verbose_name_plural': '协议信息',
            },
        ),
        migrations.CreateModel(
            name='Raw_data_lora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, verbose_name='系统ID')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='服务器时间')),
                ('tmst', models.CharField(max_length=30, verbose_name='报文时间')),
                ('freq', models.CharField(max_length=20, verbose_name='工作频点')),
                ('basestation_mac', models.CharField(max_length=20, verbose_name='基站MAC')),
                ('basestation_ip', models.CharField(default='127.1.1.2', max_length=20, null=True, verbose_name='基站IP')),
                ('basestation_port', models.CharField(default='6666', max_length=20, null=True, verbose_name='基站端口号')),
                ('snr', models.CharField(max_length=20, verbose_name='信噪比')),
                ('rssi', models.CharField(max_length=20, verbose_name='信号强度')),
                ('rawdata', models.CharField(max_length=500, verbose_name='生数据')),
            ],
            options={
                'verbose_name': '生数据_LoRa',
                'verbose_name_plural': '生数据_LoRa',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='energy_type',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='apps.Energy_type', verbose_name='能耗类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicecom', to='apps.Floor', verbose_name='所属楼层'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Protocol', verbose_name='表计协议类型'),
        ),
        migrations.AddField(
            model_name='building',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='apps.Customer', verbose_name='所属客户园区'),
        ),
    ]
