# Generated by Django 2.1 on 2018-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180805_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='客户ID(0开头6位)')),
                ('GroupName', models.CharField(max_length=50, verbose_name='GroupName(0开头6位)')),
                ('u', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电流')),
                ('i', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压')),
            ],
        ),
    ]
