# Generated by Django 2.1 on 2018-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='CH4LiuLiang',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='CH4流量'),
        ),
        migrations.AddField(
            model_name='group',
            name='H2LiuLiang',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='H2流量'),
        ),
        migrations.AddField(
            model_name='group',
            name='H2OLiuLiang',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='水流量'),
        ),
        migrations.AddField(
            model_name='group',
            name='INTemperture',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='进气口温度'),
        ),
        migrations.AddField(
            model_name='group',
            name='KQLiuLiang',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='空气流量'),
        ),
        migrations.AddField(
            model_name='group',
            name='N2LiuLiang',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='N2流量'),
        ),
        migrations.AddField(
            model_name='group',
            name='OUTTemperture',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='出气口温度'),
        ),
    ]
