# Generated by Django 2.1 on 2018-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20180805_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='KQLiuLiang',
            new_name='QAIR',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='CH4LiuLiang',
            new_name='QCH4',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='H2LiuLiang',
            new_name='QH2',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='H2OLiuLiang',
            new_name='QH2O',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='N2LiuLiang',
            new_name='QN2',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='INTemperture',
            new_name='TIN',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='OUTTemperture',
            new_name='TOUT',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='u',
            new_name='U',
        ),
        migrations.RemoveField(
            model_name='group',
            name='i',
        ),
        migrations.AddField(
            model_name='group',
            name='I',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='电压'),
        ),
        migrations.AddField(
            model_name='group',
            name='t',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
