# Generated by Django 2.1 on 2018-08-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20180805_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='t',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
