# Generated by Django 2.1 on 2018-08-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20180808_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='cell',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='系统ID')),
                ('boxNum', models.IntegerField(default=0, verbose_name='箱号')),
                ('chnNum', models.IntegerField(default=0, verbose_name='通道号')),
                ('i', models.IntegerField(default=0, verbose_name='实时电流')),
                ('u', models.IntegerField(default=0, verbose_name='实时电压')),
                ('q', models.IntegerField(default=0, verbose_name='实时容量')),
                ('qA', models.IntegerField(default=0, verbose_name='累计容量')),
                ('r', models.IntegerField(default=0, verbose_name='当前内阻')),
                ('T', models.IntegerField(default=0, verbose_name='当前温度')),
                ('n', models.IntegerField(default=0, verbose_name='当前工步号')),
                ('k', models.IntegerField(default=0, verbose_name='当前过程号')),
                ('state', models.IntegerField(default=0, verbose_name='通道状态')),
                ('mode', models.IntegerField(default=0, verbose_name='工作模式')),
                ('tc', models.IntegerField(default=0, verbose_name='本工步已完成时间')),
                ('ta', models.IntegerField(default=0, verbose_name='本工步累计时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='systeminfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
