# Generated by Django 2.1 on 2018-08-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtestinfotable',
            name='wdjID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.wdjDeviceTable', verbose_name='wdjID'),
        ),
    ]
